Added declaration file for easier typings when using TypeScript
coopflow/fastify-mailer pull request #13
Opened 2021-05-09 12:42 UTC by yusuf-khamis

Consider merging, had issue with typings so had to make the update

2021-05-13 14:19 UTC, coopflow commented
Would you mind to add tests for those types ?

2021-05-16 12:52 UTC, yusuf-khamis commented
> Would you mind to add tests for those types ?

I have added the unit tests, until today i was not aware of unit tests for typings, so I did my best, review and merge.

2021-05-17 13:05 UTC, coopflow requested changes

2021-05-17 13:20 UTC, coopflow commented
> 
> 
> Consider merging, **had issue with typings** so had to make the update

To be honest I don't think that I will merge this PR:
- Types for nodemailer are not officially supported by its author Andris Reinman.
- I already have a private branch with types from @types/nodemailer (you can now see it [here](https://github.com/coopflow/fastify-mailer/tree/typescript))
- DefinitelyTyped community maintained types often lead to unexpected breaking changes from versions to versions.

If you want to use those types I strongly suggest that you re-declare the `mailer` interface in the `fastify` module within your own code to add the properties you expect:
eg.:
```ts
import { Transporter} from "nodemailer";

export interface FastifyMailerNamedInstance {
  [namespace: string]: Transporter;
}
export type FastifyMailer = FastifyMailerNamedInstance & Transporter;

declare module "fastify" {
  interface FastifyInstance {
    mailer: FastifyMailer;
  }
}
```

2021-05-17 13:20 UTC, closed without merging